name: Desktop - Build and publish electron app

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Cache Electron (Windows)
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\electron\Cache
            ~\AppData\Local\electron-builder\Cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Extract version from tag
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF -replace '^refs/tags/v',''
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Set version and commit SHA into build.ts
        shell: pwsh
        run: |
          $content = @"

          // This file is auto-generated during CI/CD
          const VERSION = "$env:VERSION";
          const SHA = "${{ github.sha }}";

          export const build = {
              version: VERSION,
              sha: SHA
          };

          "@
          Set-Content -Path "./packages/core/src/types/build.ts" -Value $content

      - name: Update package.json version
        shell: bash
        working-directory: apps/desktop
        run: npm version ${VERSION} --no-git-tag-version

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}
          LOCAL_ONLY: true
          NODE_ENV: production
        working-directory: apps/desktop
        run: npm run publish -- --win

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Cache Electron (macOS)
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/electron
            ~/Library/Caches/electron-builder
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set version and commit SHA into build.ts
        run: |
          cat <<EOF > ./packages/core/src/types/build.ts
          // This file is auto-generated during CI/CD
          const VERSION = "${VERSION}";
          const SHA = "${{ github.sha }}";

          export const build = {
              version: VERSION,
              sha: SHA
          };
          EOF

      - name: Update package.json version
        working-directory: apps/desktop
        run: npm version $VERSION --no-git-tag-version

      - name: Install Dependencies
        run: |
          npm ci

      - name: Publish and Notarize Electron App (macOS Apple Silicon)
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}
          LOCAL_ONLY: true
          NODE_ENV: production
        working-directory: apps/desktop
        run: |
          npm run publish -- --mac --arch="arm64"

      - name: Publish and Notarize Electron App (macOS Intel)
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}
          LOCAL_ONLY: true
          NODE_ENV: production
        working-directory: apps/desktop
        run: |
          npm run publish -- --mac --arch="x64"
